"""added quiz attempt entity

Revision ID: 6c0ec11be616
Revises: ea1a7b83caa1
Create Date: 2025-05-18 00:17:30.512560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c0ec11be616'
down_revision = 'ea1a7b83caa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_quiz_answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attempt_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'quiz_attempts', ['attempt_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_quiz_answers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('attempt_id')

    # ### end Alembic commands ###
