"""added 2 fields to email entity for prediction

Revision ID: e876d29cf2a4
Revises: 
Create Date: 2025-05-10 15:38:58.746254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e876d29cf2a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text_prediction', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('url_prediction', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.drop_column('url_prediction')
        batch_op.drop_column('text_prediction')

    # ### end Alembic commands ###
